Models/ServiceType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SparkAuto.Models
{
    public class ServiceType
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public double Price { get; set; }
    }
}

Pages/Cars/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SparkAuto.Data;
using SparkAuto.Models;

namespace SparkAuto.Pages.Cars
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public Car Car { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult OnGet(string userId=null)
        {
            Car = new Car();
            if (userId == null)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                userId = claim.Value;
            }
            Car.UserId = userId;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.Car.Add(Car);
            await _db.SaveChangesAsync();
            StatusMessage = "Car has been added successfully";
            return RedirectToPage("Index", new { userId = Car.UserId });
        }

    }
}

Pages/ServiceTypes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SparkAuto.Data;
using SparkAuto.Models;

namespace SparkAuto.Pages.ServiceTypes
{
    [Authorize(Roles = Utility.SD.AdminEndUser)]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public ServiceType ServiceType { get; set; }

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.ServiceType.Add(ServiceType);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }

    }
}

Pages/ServiceTypes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAuto.Data;
using SparkAuto.Models;

namespace SparkAuto.Pages.ServiceTypes
{
    [Authorize(Roles = Utility.SD.AdminEndUser)]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public DetailsModel(SparkAuto.Data.ApplicationDbContext db)
        {
            _db = db;
        }

        public ServiceType ServiceType { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ServiceType = await _db.ServiceType.FirstOrDefaultAsync(m => m.Id == id);

            if (ServiceType == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Services/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAuto.Data;
using SparkAuto.Models;
using SparkAuto.Models.ViewModel;
using SparkAuto.Utility;

namespace SparkAuto.Pages.Services
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public CarServiceViewModel CarServiceVM { get; set; }
        //public double Tax { get; set; }
        //public double FullPrice { get; set; }

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public CommonValues cv {get;set;}

        public async Task<IActionResult> OnGet(int carId)
        {
            CarServiceVM = new CarServiceViewModel
            {
                Car = await _db.Car.Include(c => c.ApplicationUser).FirstOrDefaultAsync(c => c.Id == carId),
                ServiceHeader = new Models.ServiceHeader()
            };

            cv = _db.CommonValues.Find(1);

            List<String> lstServiceTypeInShoppingCart = _db.ServiceShoppingCart
                                                            .Include(c => c.ServiceType)
                                                            .Where(c => c.CarId == carId)
                                                            .Select(c => c.ServiceType.Name)
                                                            .ToList();

            IQueryable<ServiceType> lstService = from s in _db.ServiceType
                                                 where !(lstServiceTypeInShoppingCart.Contains(s.Name))
                                                 select s;

            CarServiceVM.ServiceTypesList = lstService.ToList();

            CarServiceVM.ServiceShoppingCart = _db.ServiceShoppingCart
                                                     .Include(c => c.ServiceType)
                                                     .Where(c => c.CarId == carId)
                                                     .ToList();
            CarServiceVM.ServiceHeader.TotalPrice = 0;
            CarServiceVM.ServiceHeader.Tax = 0;
            

            foreach (var item in CarServiceVM.ServiceShoppingCart)
            {

                CarServiceVM.ServiceHeader.TotalPrice += item.ServiceType.Price * item.Quantity;
                CarServiceVM.ServiceHeader.TotalPrice = Math.Round(CarServiceVM.ServiceHeader.TotalPrice, 2);
                CarServiceVM.ServiceHeader.Tax = CarServiceVM.ServiceHeader.TotalPrice * cv.iva;
                CarServiceVM.ServiceHeader.Tax = Math.Round(CarServiceVM.ServiceHeader.Tax, 2);
                CarServiceVM.ServiceHeader.EnvCharge = cv.envCharge;
                CarServiceVM.ServiceHeader.FullPrice = CarServiceVM.ServiceHeader.Tax + CarServiceVM.ServiceHeader.TotalPrice + CarServiceVM.ServiceHeader.EnvCharge;
                CarServiceVM.ServiceHeader.FullPrice = Math.Round(CarServiceVM.ServiceHeader.FullPrice, 2);
            }

            return Page();

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                CarServiceVM.ServiceHeader.DateAdded = DateTime.Now;
                CarServiceVM.ServiceHeader.NextServiceDate = DateTime.Now.AddDays(90);

                CommonValues cv2 = _db.CommonValues.Find(1);

                CarServiceVM.ServiceShoppingCart = _db.ServiceShoppingCart.Include(c => c.ServiceType).Where(c => c.CarId == CarServiceVM.Car.Id).ToList();
                foreach (var item in CarServiceVM.ServiceShoppingCart)
                {
                    CarServiceVM.ServiceHeader.TotalPrice += item.ServiceType.Price * item.Quantity;
                    CarServiceVM.ServiceHeader.TotalPrice = Math.Round(CarServiceVM.ServiceHeader.TotalPrice, 2);
                    CarServiceVM.ServiceHeader.Tax = CarServiceVM.ServiceHeader.TotalPrice * cv2.iva;
                    CarServiceVM.ServiceHeader.Tax = Math.Round(CarServiceVM.ServiceHeader.Tax, 2);
                    CarServiceVM.ServiceHeader.EnvCharge = cv2.envCharge;
                    CarServiceVM.ServiceHeader.FullPrice = CarServiceVM.ServiceHeader.Tax + CarServiceVM.ServiceHeader.TotalPrice + CarServiceVM.ServiceHeader.EnvCharge;
                    CarServiceVM.ServiceHeader.FullPrice = Math.Round(CarServiceVM.ServiceHeader.FullPrice, 2);
                }
                CarServiceVM.ServiceHeader.CarId = CarServiceVM.Car.Id;

                _db.ServiceHeader.Add(CarServiceVM.ServiceHeader);
                await _db.SaveChangesAsync();

                foreach (var detail in CarServiceVM.ServiceShoppingCart)
                {
                    Console.WriteLine(detail.ServiceType.Price);

                    ServiceDetails serviceDetails = new ServiceDetails
                    {
                        ServiceHeaderId = CarServiceVM.ServiceHeader.Id,
                        ServiceName = detail.ServiceType.Name,
                        ServicePrice = detail.ServiceType.Price,
                        ServiceTypeId = detail.ServiceTypeId,
                        Quantity = detail.Quantity
                    };
                    _db.ServiceDetails.Add(serviceDetails);

                }

                _db.ServiceShoppingCart.RemoveRange(CarServiceVM.ServiceShoppingCart);

                //ACTUALIZACION DE MILLAS 
                CarServiceVM.Car.Miles = CarServiceVM.ServiceHeader.Miles;
                _db.Car.Attach(CarServiceVM.Car);
                _db.Entry(CarServiceVM.Car).Property(x => x.Miles).IsModified = true;

                await _db.SaveChangesAsync();
                return RedirectToPage("../Cars/Index", new { userId = CarServiceVM.Car.UserId });
            }

            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }

        public async Task<IActionResult> OnPostAddToCart()
        {
            ServiceShoppingCart objServiceCart = new ServiceShoppingCart()
            {
                CarId = CarServiceVM.Car.Id,
                ServiceTypeId = CarServiceVM.ServiceDetails.ServiceTypeId,
                Quantity = CarServiceVM.ServiceDetails.Quantity
            };

            _db.ServiceShoppingCart.Add(objServiceCart);
            await _db.SaveChangesAsync();
            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }

        public async Task<IActionResult> OnPostRemoveFromCart(int serviceTypeId)
        {
            ServiceShoppingCart objServiceCart = _db.ServiceShoppingCart
                .FirstOrDefault(u => u.CarId == CarServiceVM.Car.Id && u.ServiceTypeId == serviceTypeId);


            _db.ServiceShoppingCart.Remove(objServiceCart);
            await _db.SaveChangesAsync();
            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }
    }
}

Pages/Services/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SelectPdf;
using SparkAuto.Data;
using SparkAuto.Models;

namespace SparkAuto.Pages.Services
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public DetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ServiceHeader serviceHeader { get; set; }
        public List<ServiceDetails> serviceDetails { get; set; }

        public void OnGet(int serviceId)
        {
            serviceHeader = _db.ServiceHeader.Include(s => s.Car).Include(s => s.Car.ApplicationUser).FirstOrDefault(s => s.Id == serviceId);
            serviceDetails = _db.ServiceDetails.Where(s => s.ServiceHeaderId == serviceId).ToList();
        }

    }
}

Pages/Services/History.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAuto.Data;
using SparkAuto.Models;

namespace SparkAuto.Pages.Services
{
    [Authorize]
    public class HistoryModel : PageModel
    {

        private readonly ApplicationDbContext _db;

        public HistoryModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public List<ServiceHeader> ServiceHeader { get; set; }
        public List<Car> Car { get; set; }
        public string UserId { get; set; }

        public async Task OnGet(int carId)
        {
            ServiceHeader = await _db.ServiceHeader.Include(s => s.Car).Include(c => c.Car.ApplicationUser).Where(c => c.CarId == carId).OrderByDescending(x => x.DateAdded).ToListAsync();

            UserId = _db.Car.Where(u => u.Id == carId).ToList().FirstOrDefault().UserId;
            Car = _db.Car.Include(c => c.ApplicationUser).Where(c => c.Id == carId).ToList();
        }
    }
}

Pages/Services/Create.cshtml
@page
@model SparkAuto.Pages.Services.CreateModel
@{ ViewData["Title"] = "Create Service";
    Layout = "~/Pages/Shared/_Layout.cshtml"; 
}

<header class="page-header bg-primary pb-10">
    <div class="container py-4">
        <div class="row">
            <div class="col-9">
                <a asp-page="../Cars/Index" asp-route-userId="@Model.CarServiceVM.Car.UserId" class="btn btn-sm btn-outline-white btn-icon">
                    <i class="fal fa-arrow-left"></i>
                </a>
                <h2 class="text-white mt-2">Create New Service</h2>
            </div>
            <div class="col"></div>
        </div>
    </div>
</header>

<div class="container mt-n10">
    <div class="row">

        <div class="col-12 col-md-6">
            <div class="card card-icon">
                <div class="row no-gutters">
                    <div class="col-auto card-icon-aside bg-white">
                        <i class="fal fa-user"></i>
                    </div>
                    <div class="col align-self-center">
                        <div class="card-body">
                            <h5 class="card-title mb-0">@Model.CarServiceVM.Car.ApplicationUser.Name</h5>
                            <p class="card-text m-0 p-0">@Model.CarServiceVM.Car.ApplicationUser.Email / @Model.CarServiceVM.Car.ApplicationUser.PhoneNumber</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 mt-4 mt-md-0">
            <div class="card card-icon">
                <div class="row no-gutters">
                    <div class="col-auto card-icon-aside bg-white">
                        <i class="fal fa-car"></i>
                    </div>
                    <div class="col align-self-center">
                        <div class="card-body">
                            <h5 class="card-title mb-0">@Model.CarServiceVM.Car.Make @Model.CarServiceVM.Car.Model @Model.CarServiceVM.Car.Style</h5>
                            <p class="card-text">@Model.CarServiceVM.Car.Year / @Model.CarServiceVM.Car.Miles kms</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>




<div class="container mt-4">
    <div class="card">

        <div class="card-body">
            <form method="post" style="width:100%">
                <div class="container">
                    <input hidden asp-for="CarServiceVM.Car.Make" />
                    <input hidden asp-for="CarServiceVM.Car.Model" />
                    <input hidden asp-for="CarServiceVM.Car.VIN" />
                    <input hidden asp-for="CarServiceVM.Car.UserId" />
                    <input hidden asp-for="CarServiceVM.Car.Id" />
                    <input hidden asp-for="CarServiceVM.Car.Year" />

                    <div class="">
                        <div class="row">
                            <div class="col-7">
                                <h4 class="text-primary">Add Service</h4>
                            </div>
                            <div class="col-3">
                                <label for="">Qty</label>
                            </div>
                        </div>
                        <div class="row">
                            @if (Model.CarServiceVM.ServiceTypesList.Count == 0)
                            {
                                <p>All services have been added.</p> 
                            }
                            else
                            {
                                <div class="col-10 col-md-7">
                                    <select asp-for="CarServiceVM.ServiceDetails.ServiceTypeId"
                                            asp-items="@(new SelectList(Model.CarServiceVM.ServiceTypesList, "Id", "Name"))"
                                            class="form-control">
                                    </select>
                                </div>
                                <div class="col-md-2">
                                    <input type="number" asp-for="CarServiceVM.ServiceDetails.Quantity" class="form-control" min="1" max="100" value="1">
                                </div>


                                <div class="col-2 col-md-1">
                                    <button type="submit" asp-page-handler="AddToCart" class="btn btn-primary btn-icon">
                                        <i class="fal fa-plus"></i>
                                    </button>
                                </div>
                            }
                        </div>
                    </div>


                    <div class="mt-4">
                        <h3 class="text-primary pb-2">Service Summary</h3>
                        @if (Model.CarServiceVM.ServiceShoppingCart.Count == 0)
                        {
                            <p>No service has been added yet. Please add a service to be performed.</p> 
                        }
                        else
                        {
                            <div class="row mt-3">
                                <div class="col-12 col-md-7">
                                    <table class="table table-bordered table-responsive table-sm">
                                        <tr class="">
                                            <th class="fit">
                                                @Html.DisplayNameFor(m => Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Name)
                                            </th>
                                            <th class="fit">
                                                @Html.DisplayNameFor(m => Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Price)
                                            </th>
                                            <th class="fit td-center">Qty</th>
                                            <th class="fit td-center">Total</th>
                                            <th class="fit td-center">Actions</th>
                                        </tr>

                                        @foreach (var item in Model.CarServiceVM.ServiceShoppingCart)
                                        {
                                            <tr>
                                                <td class="fit">
                                                    @Html.DisplayFor(m => item.ServiceType.Name)
                                                </td>
                                                <td class="fit">
                                                    @String.Format("${0:0.00}",item.ServiceType.Price)
                                                </td>
                                                <td class="fit">
                                                    @Html.DisplayFor(m => item.Quantity)
                                                </td>
                                                <td class="fit">
                                                    @String.Format("${0:0.00}",item.Quantity * item.ServiceType.Price)
                                                </td>
                                                <td class="fit td-center">
                                                    <button type="submit" asp-page-handler="RemoveFromCart" asp-route-serviceTypeId="@item.ServiceTypeId" class="btn btn-danger btn-sm">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        }
                                        <tr style="background-color: none">
                                            <td colspan="3" class="fit">
                                                <h6 class="text-success">Sub-Total:</h6>
                                            </td>
                                            <td colspan="2" class="fit">
                                                <h6 class="text-success">@(String.Format("${0:0.00}",Model.CarServiceVM.ServiceHeader.TotalPrice))</h6>
                                            </td>
                                        </tr>
                                        <tr style="background-color: none">
                                            <td colspan="3" class="fit">
                                                <h6 class="text-success">Tax:</h6>
                                            </td>
                                            <td colspan="2" class="fit">
                                                <h6 class="text-success">@(String.Format("${0:0.00}",Model.CarServiceVM.ServiceHeader.Tax))</h6>
                                            </td>
                                        </tr>
                                        <tr style="background-color: none">
                                            <td colspan="3" class="fit">
                                                <h6 class="text-success">Env Charge:</h6>
                                            </td>
                                            <td colspan="2" class="fit">
                                                <h6 class="text-success">@(String.Format("${0:0.00}",Model.cv.envCharge))</h6>
                                            </td>
                                        </tr>
                                        <tr style="background-color:#e2fee2">
                                            <td colspan="3" class="fit">
                                                <h6 class="text-success">Total Price:</h6>
                                            </td>
                                            <td colspan="2" class="fit">
                                                <h6 class="text-success">@(String.Format("${0:0.00}",Model.CarServiceVM.ServiceHeader.FullPrice))</h6>
                                            </td>
                                        </tr>

                                    </table>
                                </div>
                                <div class="col-12 col-md-5">
                                    <div class="row">
                                        <div class="col-12">
                                            <label asp-for="CarServiceVM.ServiceHeader.Miles"></label>
                                        </div>
                                        <div class="col-12">
                                            <input type="hidden" value=@(Model.CarServiceVM.Car.Miles) id="Lastmiles">
                                            <input asp-for="CarServiceVM.ServiceHeader.Miles" id="txtMiles" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row py-2">
                                        <div class="col-12">
                                            <textarea placeholder="Comments..." asp-for="CarServiceVM.ServiceHeader.Details" class="form-control" style="height:100px">
                                        </textarea>
                                        </div>
                                    </div>
                                    <div class="row p-0">
                                        <div class="col-12">
                                            <button class="btn btn-success rounded-pill" onclick="return validateInput()">Service Completed</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        }
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>
        function validateInput() {
            var miles = parseInt($("#txtMiles").val());
            var lastmiles = parseInt($("#Lastmiles").val());

            if (miles < lastmiles) {
                swal("Error!","The kilometers entered must be greater than or equal to the previous record (" + lastmiles + " kilometers)","error");
                return false;
            }

            return true;
        }
    </script>

}

Pages/Services/Details.cshtml
@page
@model SparkAuto.Pages.Services.DetailsModel
@{ ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml"; 
}

<header class="page-header bg-primary pb-10">
    <div class="container py-4">
        <div class="row">
            <div class="col-12">
                <a asp-page="../Services/History" asp-route-carId="@Model.serviceHeader.CarId" class="btn btn-sm btn-icon btn-outline-light"><i class="fal fa-arrow-left"></i></a>
            </div>
            <div class="col-12">
                <h2 class="text-white mt-2">Service Details</h2>
            </div>
        </div>
    </div>
</header>

<div class="container mt-n10">
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="card card-icon">
                <div class="row no-gutters">
                    <div class="col-auto card-icon-aside bg-white">
                        <i class="far fa-user"></i>
                    </div>
                    <div class="col align-self-center">
                        <div class="card-body">
                            <h5 class="card-title mb-0">@Model.serviceHeader.Car.ApplicationUser.Name</h5>
                            <p class="text-body">@Model.serviceHeader.Car.ApplicationUser.Email / @Model.serviceHeader.Car.ApplicationUser.PhoneNumber</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="card card-icon">
                <div class="row no-gutters">
                    <div class="col-auto card-icon-aside bg-white">
                        <i class="fal fa-car"></i>
                    </div>
                    <div class="col align-self-center">
                        <div class="card-body">
                            <h5 class="card-title mb-0">@Model.serviceHeader.Car.Make @Model.serviceHeader.Car.Model @Model.serviceHeader.Car.Style</h5>
                            <p class="text-body">@Model.serviceHeader.Car.Year</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="card p-4">
        <div class="row">
            <div class="col-7">
                <table class="table table-bordered">
                    <tr>
                        <th class="text-secondary">
                            @Html.DisplayNameFor(m => Model.serviceDetails[0].ServiceName)
                        </th>
                        <th class="text-secondary">
                            @Html.DisplayNameFor(m => Model.serviceDetails[0].ServicePrice)
                        </th>
                        <th class="text-secondary">
                            Service Total
                        </th>
                    </tr>
                    @foreach (var item in Model.serviceDetails)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.ServiceName) x @item.Quantity
                            </td>
                            <td>
                                @(String.Format("${0:0.00}",item.ServicePrice ))
                            </td>
                            <td>
                                @(String.Format("${0:0.00}",item.ServicePrice * item.Quantity ))
                            </td>

                        </tr>
                    }
                    <tr>
                        <th colspan="2">Total Price:</th>
                        <td colspan="1">
                            <h6 class="text-success">@(String.Format("${0:0.00}",Model.serviceHeader.TotalPrice))</h6>
                        </td>
                    </tr>
                    <tr>
                        <th colspan="2">Taxes:</th>
                        <td colspan="1">
                            <h6 class="text-success">@(String.Format("${0:0.00}",Model.serviceHeader.Tax))</h6>
                        </td>
                    </tr>
                     <tr>
                        <th colspan="2">Env Charge:</th>
                        <td colspan="1">
                            <h6 class="text-success">@(String.Format("${0:0.00}",Model.serviceHeader.EnvCharge))</h6>
                        </td>
                    </tr>
                    <tr class="bg-success-soft">
                        <td colspan="2">
                            <h6 class="text-success">Full Price :</h6>
                        </td>
                        <td colspan="1">
                            <h6 class="text-success">@(String.Format("${0:0.00}",Model.serviceHeader.FullPrice))</h6>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-5">
                <div class="row">
                    <div class="col-12">
                        <label asp-for="serviceHeader.Miles" ></label>
                    </div>
                    <div class="col-12">
                        <input asp-for="serviceHeader.Miles" readonly id="txtMiles" class="form-control" />
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-12">
                        <textarea placeholder="Comments..." readonly asp-for="serviceHeader.Details" class="form-control" style="height:100px"></textarea>                                      
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>